# Numpy-Log

In [1]:
import numpy as np

## Functions

In [2]:
# 1. np.log()  # Natural log
# 2. np.log2()
# 3. np.log10()

# This functions are used to reduce skewness of data

### 1. np.log() (Natural Log)

In [2]:
np.log(34)

np.float64(3.5263605246161616)

In [3]:
np.log(-10) # we can not find the log of Negative Number, It gives Not a Number

C:\Users\admin\AppData\Local\Temp\ipykernel_16484\1670060136.py:1: RuntimeWarning: invalid value encountered in log
  np.log(-10) # we can not find the log of Negative Number, It gives Not a Number

np.float64(nan)

In [5]:
np.log(0) # -infinity

C:\Users\admin\AppData\Local\Temp\ipykernel_30880\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)

np.float64(-inf)

In [6]:
np.log(1) # 0

np.float64(0.0)

### 2. np.log2()

In [8]:
np.log2(34)

np.float64(5.087462841250339)

In [10]:
np.log2(10)

np.float64(3.321928094887362)

### 3. np.log10()

In [13]:
np.log10(34)

np.float64(1.5314789170422551)

In [14]:
np.log10(10)

np.float64(1.0)

## log Transformation

In [ ]:
# the above logarithmic functions are used in log transformation

In [3]:
import pandas as pd

In [2]:
import numpy as np

In [6]:
dict1 = {"Age":np.random.randint(20, 50, size = 10),
         "Height":np.random.randint(160, 180, size = 10),
         "Weight":np.random.randint(60,80, size = 10)
        }
dict1

{'Age': array([34, 26, 44, 39, 27, 22, 32, 31, 21, 34], dtype=int32),
 'Height': array([160, 173, 177, 175, 166, 167, 163, 167, 175, 174], dtype=int32),
 'Weight': array([61, 61, 73, 76, 68, 63, 69, 74, 72, 71], dtype=int32)}

In [8]:
df = pd.DataFrame(dict1)
df

   Age  Height  Weight
0   34     160      61
1   26     173      61
2   44     177      73
3   39     175      76
4   27     166      68
5   22     167      63
6   32     163      69
7   31     167      74
8   21     175      72
9   34     174      71

In [18]:
np.log(df['Weight']) # this is transformation of data

In [20]:
df

   Age  Height    Weight
0   34     160  1.413636
1   26     173  1.413636
2   44     177  1.456394
3   39     175  1.465737
4   27     166  1.439718
5   22     167  1.421453
6   32     163  1.443172
7   31     167  1.459560
8   21     175  1.453174
9   34     174  1.449898

In [21]:
dict2 = {"Age":np.random.randint(20, 50, size = 10),
         "Height":np.random.randint(160, 180, size = 10),
         "Weight":np.random.randint(60,80, size = 10)
        }
dict2

{'Age': array([36, 41, 36, 24, 25, 44, 36, 33, 29, 23], dtype=int32),
 'Height': array([167, 167, 161, 169, 176, 175, 175, 176, 164, 165], dtype=int32),
 'Weight': array([69, 71, 69, 62, 71, 64, 76, 77, 66, 78], dtype=int32)}

In [22]:
df = pd.DataFrame(dict2)
df

   Age  Height  Weight
0   36     167      69
1   41     167      71
2   36     161      69
3   24     169      62
4   25     176      71
5   44     175      64
6   36     175      76
7   33     176      77
8   29     164      66
9   23     165      78

In [23]:
np.log(df) # This is transformation(log Transformation) , All the values returned are the log of dataframe

        Age    Height    Weight
0  3.583519  5.117994  4.234107
1  3.713572  5.117994  4.262680
2  3.583519  5.081404  4.234107
3  3.178054  5.129899  4.127134
4  3.218876  5.170484  4.262680
5  3.784190  5.164786  4.158883
6  3.583519  5.164786  4.330733
7  3.496508  5.170484  4.343805
8  3.367296  5.099866  4.189655
9  3.135494  5.105945  4.356709

In [24]:
# for decreasing the skewness of data we transform the data
# Skewness ->> search on net