In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
titanic = sns.load_dataset('titanic')

In [7]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [10]:
df = titanic.drop(columns =['sex','sibsp','parch','embarked','class','who','embark_town','alive','alone','adult_male','deck'])

In [12]:
df.head()

   survived  pclass   age     fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   age       714 non-null    float64
 3   fare      891 non-null    float64
dtypes: float64(2), int64(2)
memory usage: 28.0 KB

In [14]:
df.shape

(891, 4)

In [16]:
df.isnull().sum()

survived      0
pclass        0
age         177
fare          0
dtype: int64

In [17]:
df.isnull().mean()*100

survived     0.00000
pclass       0.00000
age         19.86532
fare         0.00000
dtype: float64

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X = df.drop(columns = ['survived'])
y = df['survived']

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 2)

In [38]:
X_train.head()

     pclass   age     fare
30        1  40.0  27.7208
10        3   4.0  16.7000
873       3  47.0   9.0000
182       3   9.0  31.3875
876       3  20.0   9.8458

In [39]:
from sklearn.impute import KNNImputer

In [75]:
knn = KNNImputer(n_neighbors = 5, weights = 'distance') # weights = 'distance'/'uniform'

X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

In [73]:
pd.DataFrame(X_train_trf, columns = X_train.columns)

     pclass        age      fare
0       1.0  40.000000   27.7208
1       3.0   4.000000   16.7000
2       3.0  47.000000    9.0000
3       3.0   9.000000   31.3875
4       3.0  20.000000    9.8458
..      ...        ...       ...
707     3.0  30.000000    8.6625
708     3.0  25.047962    8.7125
709     1.0  71.000000   49.5042
710     1.0  29.530076  221.7792
711     1.0  49.275927   25.9250

[712 rows x 3 columns]

In [53]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [76]:
lr = LogisticRegression()

lr.fit(X_train_trf, y_train)

y_pred = lr.predict(X_test_trf)

accuracy_score(y_test,y_pred)

0.7039106145251397

In [56]:
# Simple Imputer --> mean
from sklearn.impute import SimpleImputer
si = SimpleImputer(strategy = 'mean')

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.fit_transform(X_test)

In [78]:
lr2 = LogisticRegression()
lr2.fit(X_train_trf2, y_train)
y_pred2 = lr2.predict(X_test_trf2)

accuracy_score(y_pred2, y_test)

0.6927374301675978

In [79]:
# It is seen that with simple Imputer accuracy is less and Using KNN Imputer Accuracy increases.