In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = {
'Age':[22, 58, np.nan, 42, np.nan, 71, 37, 94, 
       np.nan,  6, 12, 33, 74, 64, 70,  9, 34,
       21, 54, 41, 25, 56, np.nan, 12, 12, 62, 25, 13, 32, 58, 86, 38, 51, 95,
       35, 10, 99, 90,  2, 98, 46, 23, 30, 83,  3,  4, 16, 81, 24, 79],
'Value':[72, 14, 36, 44, 15, 55, 83, 61, 76, 96, 54, 77, 12, 92, 81, 82, 26,
       43, 75, 50, 99, 10, 98, 50, 71, 44, 27, 73, 36,  8, 64, 84, 49,  1,
       74, 25, 16, 74, 67, 40, 62, 91, 43, 46, 67, 41, 30, 77, 57, 18]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df.head()

    Age  Value
0  22.0     72
1  58.0     14
2   NaN     36
3  42.0     44
4   NaN     15

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

In [6]:
imputer_mean = SimpleImputer(strategy = 'mean')

In [14]:
X = df.drop('Value', axis =1)
y = df.drop('Age',axis =1)

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [16]:
X_train.head()

     Age
12  74.0
4    NaN
37  90.0
8    NaN
3   42.0

In [17]:
X_test.head()

     Age
13  64.0
39  98.0
30  86.0
45   4.0
17  21.0

In [19]:
X_train = imputer_mean.fit_transform(X_train)
X_test = imputer_mean.fit_transform(X_test)

In [20]:
X_train

array([[74.        ],
       [43.16666667],
       [90.        ],
       [43.16666667],
       [42.        ],
       [37.        ],
       [23.        ],
       [16.        ],
       [81.        ],
       [ 9.        ],
       [ 6.        ],
       [34.        ],
       [12.        ],
       [35.        ],
       [38.        ],
       [22.        ],
       [ 3.        ],
       [13.        ],
       [95.        ],
       [71.        ],
       [58.        ],
       [33.        ],
       [99.        ],
       [58.        ],
       [56.        ],
       [43.16666667],
       [83.        ],
       [10.        ],
       [12.        ],
       [46.        ],
       [12.        ],
       [43.16666667],
       [54.        ],
       [79.        ],
       [25.        ],
       [94.        ],
       [30.        ],
       [70.        ],
       [32.        ],
       [ 2.        ]])

In [21]:
X_test

array([[64.],
       [98.],
       [86.],
       [ 4.],
       [21.],
       [24.],
       [25.],
       [62.],
       [51.],
       [41.]])