- It is also called as MICE Imputation.
- MICE - Multivariate Imputer by Chaining Equation
- It is a Iterative process to impute the value.

- The Main thing is --> it only applied on input data.

In [2]:
import numpy as np
import pandas as pd
import  matplotlib.pyplot as plt
import seaborn as sns

In [47]:
df = pd.DataFrame(
    {
        'Age' : [25,30,np.nan,20,59,20,24,np.nan,60,85],
        'Salary' : [30000,28000,20500,36000,50000,20000,49000,70303,90333,86000],
        'Experience':[2,np.nan,4,6,3,5,9,6,1,np.nan]
    }
)

In [48]:
df

    Age  Salary  Experience
0  25.0   30000         2.0
1  30.0   28000         NaN
2   NaN   20500         4.0
3  20.0   36000         6.0
4  59.0   50000         3.0
5  20.0   20000         5.0
6  24.0   49000         9.0
7   NaN   70303         6.0
8  60.0   90333         1.0
9  85.0   86000         NaN

In [59]:
X = df.drop(columns = ['Salary'])
y = df['Salary']

In [65]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.4, random_state = 2)

In [66]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [67]:
mice_imputer = IterativeImputer(max_iter = 10, random_state = 42)

imputed_array_X_train = mice_imputer.fit_transform(X_train)

df_imputed_X_train = pd.DataFrame(imputed_array_X_train,columns = ['Age','Experience'])

imputed_array_X_test = mice_imputer.fit_transform(X_test)

In [68]:
df_imputed_X_train

         Age  Experience
0  32.688410    6.000000
1  44.021965    4.000000
2  20.000000    6.000000
3  24.000000    9.000000
4  85.000000   -2.278568
5  60.000000    1.000000

In [72]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)

ValueError: Input X contains NaN.
LinearRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [43]:
y_pred

array([3.17950508, 4.36501269])

In [44]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
r2_score(y_pred, y_test)

0.52474995855888

In [45]:
mean_absolute_error(y_test, y_pred)

0.3644081655827418

In [46]:
mean_squared_error(y_pred, y_test)

0.16698246380585371